esphome:
  name: control-panel-ground-floor
  friendly_name: Control Panel Ground Floor

substitutions:
  home_page: lighting_1

packages:
  common: !include common.yaml
  device: !include devices/ESP32-8048S043.yaml
  layout: !include layouts/800x480.yaml
